name: "CI: Lint"
on: [push]
jobs:
  eslint-check:
    name: ESLint
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: src
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npx eslint . --ext .json,.js
