name: "CD: Crosspost Changelog"
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: "Parse release name"
      id: "get-release-name"
      run: "echo ::set-output name=name::${RELEASE:-$TAG}"
      env:
        RELEASE: ${{ github.event.release.name }}
        TAG: ${{ github.event.release.tag_name }}
    - name: "Crosspost changelog to Discord"
      id: "crosspost-action"
      uses: kludge-cs/gitcord-release-changelogger@v2
      with:
        discord-webhook: ${{ secrets.RELEASE_WEBHOOK }}
        release-body: ${{ github.event.release.body }}
        release-name: ${{ steps.get-release-name.outputs.name }}
    - name: "Log API response"
      id: "crosspost-response"
      run: "echo ${{ steps.crosspost-action.outputs.discord-api-result }}"
